--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: pvc-d8
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 5Gi
--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: pvc-mariadb
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 5Gi
